Portal/Portal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('core.urls')),
]

Portal/core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
	url('^$', views.home, name='home_page'),
	url(r'^personal_information/$', views.information_update, name='info_update'),
	url(r'^fee_statement/$', views.fees, name='fees_page'),
	url(r'^teaching_timetable/$', views.timetable, name='timetable'),
	url(r'^course_registration/$', views.course, name='course'),
	url(r'^results_slip/$', views.results, name='results'),
	url(r'^requests/$', views.requests, name='requests'),
	url(r'^login/$', views.Login, name='login_page'),
	url(r'^logout', views.Logout, name='logout_page'),
]

Portal/core/models.py
from django.db import models

# Create your models here.

Portal/core/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url='/login/')
def home(request):
	return render(request, 'index.html')

@login_required(login_url='/login/')
def information_update(request):
	return render(request, 'information_update.html')

@login_required(login_url='/login/')
def fees(request):
	return render(request, 'fees.html')

@login_required(login_url='/login/')
def timetable(request):
	return render(request, 'timetable.html')

@login_required(login_url='/login/')
def course(request):
	return render(request, 'course.html')

@login_required(login_url='/login/')
def results(request):
    return render(request, 'results.html')

@login_required(login_url='/login/')
def requests(request):
    return render(request, 'request.html')


def Login(request):
	if request.method == 'POST':
		username = request.POST['regNo']
		password = request.POST['smisPass']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('/')
		else:
			return redirect('/login/')
	else:
		return render(request, 'login.html')


def Logout(request):
	logout(request)
	return redirect('/login/')

Portal/core/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta name="author" content="Mount Kenya University" />
	<meta name="description" content="Student Management Information System" />
	<meta name="keywords" content="key, words" />
	<link rel="shortcut icon" href="https://studentportal.mku.ac.ke/umis/studentportal/images/smisicon.ico" type="image/x-icon" />
    <link rel="stylesheet", href="https://studentportal.mku.ac.ke/umis/studentportal/styles/main.css"/>
	<title>Mount Kenya University : Students Online Portal</title>
</head>
<body >
	<div id="content">
		<div id="top_info">

<table border="0" align="center" cellspacing="0" cellpadding="0" width="100%">
<tr>
  <td align="left" width="1%">
<a href="#" title="Mount Kenya University Home">
 <img src="https://studentportal.mku.ac.ke/umis/studentportal/images/logoMKU.jpg" class="logoimg"/></a>
 </td>
 <td align="left">
<table border="0" align="left" cellspacing="0" cellpadding="0" >
<tr>
 <td align="left">
<h1>
<a href="{% url 'core:home_page' %}" title="Mount Kenya University Home Page">
Mount Kenya University </a>
 </h1> </td>
  </tr>
<tr>
 <td align="left">
Unlocking Infinite Possibilities
  </td>
  </tr>
</table>
  </td>
  </tr>
</table>
		</div>
        {% block nav %}
        {% endblock %}
        {% block content %}
        {% endblock %}
		<div id="footer" >
			<p class="right">&copy; 2019 <a href="">
			Mount Kenya University</a> . Hosted by
			<a href="http://www.mwanafunzi.net" title="Fountain ICT Services">Fountain ICT Services
			</a></p>
			<p><a href="">About Us</a> &middot; </p>
		</div>
	  </div>
</body>
</html>

Portal/core/templates/course.html
{% extends 'base.html' %}


{% block nav %}
<div id="navigation" role="navigation">
 <ul id="navigation-primary" class="ult-section primary">   <li class="ult-position">  <a href="{% url 'core:home_page' %}"  class="first">Home</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:info_update' %}" >Information Update</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:fees_page' %}" >Fees</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:timetable' %}" >Timetables</a>
 </li>  <li class="ult-position active">  <a href="{% url 'core:course' %}" >Course Registration</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:results' %}" >Results</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:requests' %}" >My Requests</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:logout_page' %}" >Sign Out</a>
 </li>
</ul><!-- end: .primary -->
  <ul id="navigation-secondary" class="ult-section secondary">   <li class="ult-position  active">  <a href="password_update.php"  class="first">Change Password</a>
 </li>  <li class="ult-position ">  <a href="student_clearance.php" >Student Clearance</a>
 </li>  <li class="ult-position ">  <a href="https://sites.google.com/a/mku.ac.ke/students/" >Downloads</a>
 </li>  <li class="ult-position ">  <a href="http://distance.mku.ac.ke/portal/" target="_blank" > E-Learning Portal </a>
 </li>  <li class="ult-position ">  <a href="https://ibank.gtbank.co.ke/newapps/gtcollectportal/index.aspx" target="_blank" > MPesa Trans. Validation </a>
 </li>  <li class="ult-position ">  <a href="http://studentemailreg.mku.ac.ke/" target="_blank" > Students Email </a>
 </li>
 </ul><!-- end: .secondary -->
 </div><!-- end: #navigation -->
{% endblock %}

{% block content %}
<div id="left">
	<div class="left_articles">
	<div> <p>BIT/53642/2016 KAINGU STEPHEN TUMAINI  &nbsp;  &nbsp;  &nbsp;  &nbsp; Thika (Day) , Main Campus (Thika)</p></div><p class="center">
<table border="0" align="center" cellspacing="0" cellpadding="0">
<FORM action="/umis/studentportal/course_registration.php" name="registeredCourses" enctype="multipart/form-data" method="post">
<tr><td align="center"> BIT Bachelor of Science in Information Technology</td> </tr>
<tr><td align="center"> 2018/2019 May/Aug Semester<br /> <B><FONT color=red> Registration Deadline on 08-Jun-2019 </FONT> </B> </td> </tr>
<tr><td align="center">
<table border="1" align="center" cellspacing="0" cellpadding="0">
<tr> <td align="center" colspan="8"> Registered Courses </td> </tr>
 <tr align="center"> <td > &nbsp; </td>
<td > Select  </td> <td > Code </td>  <td > Course Title </td> <td > Exam Type </td><td > Class/Group </td> <td > Status  </td> <td > Amount </td>   </tr>
 <tr align="right">  <td class="dentry_label"  colspan="7"> <input type="hidden" name="semesterID" value="2018/2019BIT2MAY/AUGTHIKADAY413006" />
 <INPUT type="hidden" name="regNo" value="BIT/53642/2016" id="regNo" />
 <INPUT type="hidden" name="regCoursesCount"
		    value="0" id="regCoursesCount" />
   Tution Charges </td>
 <td align="right">0</td>  </tr>
 <tr align="right">  <td class="dentry_label"  colspan="7">   Administrative Charges : </td>
 <td align="right">0</td>  </tr>
 <tr align="right">  <td class="dentry_label"  colspan="7">  Grand Total </td>
 <td align="right">0</td>  </tr>
</table>
</td> </tr>
</FORM></table>
 <B><FONT color=red> Sorry Course Registration closed.  <BR>Consult your Faculty/School/Institute for more Information.<BR></FONT> </B>
</p>	</div>
</div>
{% endblock %}

Portal/core/templates/index.html
{% extends 'base.html' %}

{% block nav %}
<div id="navigation" role="navigation">
 <ul id="navigation-primary" class="ult-section primary">   <li class="ult-position  active">  <a href="{% url 'core:home_page' %}"  class="first">Home</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:info_update' %}" >Information Update</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:fees_page' %}" >Fees</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:timetable' %}" >Timetables</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:course' %}" >Course Registration</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:results' %}" >Results</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:requests' %}" >My Requests</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:logout_page' %}" >Sign Out</a>
 </li>
</ul><!-- end: .primary -->
  <ul id="navigation-secondary" class="ult-section secondary">   <li class="ult-position  active">  <a href="password_update.php"  class="first">Change Password</a>
 </li>  <li class="ult-position ">  <a href="student_clearance.php" >Student Clearance</a>
 </li>  <li class="ult-position ">  <a href="https://sites.google.com/a/mku.ac.ke/students/" >Downloads</a>
 </li>  <li class="ult-position ">  <a href="http://distance.mku.ac.ke/portal/" target="_blank" > E-Learning Portal </a>
 </li>  <li class="ult-position ">  <a href="https://ibank.gtbank.co.ke/newapps/gtcollectportal/index.aspx" target="_blank" > MPesa Trans. Validation </a>
 </li>  <li class="ult-position ">  <a href="http://studentemailreg.mku.ac.ke/" target="_blank" > Students Email </a>
 </li>
 </ul><!-- end: .secondary -->
 </div><!-- end: #navigation -->
{% endblock %}

{% block content %}
<div id="left">
	<div class="left_articles"  align="center">
	    <div> <p>BIT/53642/2016 KAINGU STEPHEN TUMAINI  &nbsp;  &nbsp;  &nbsp;  &nbsp; Thika (Day) , Main Campus (Thika)</p></div>
            <table border="1" align="center" cellspacing="0" cellpadding="0" width="100%">
             <tr> <td align="center" colspan="6">
              <B> Current Notices / Events &nbsp; </B>
              </td> </tr>
             <tr> <td align="right"> &nbsp; </td><td class="colhead"> <B> Subject </B>  </td><td class="colhead"> <B> Flag </B> </td><td class="colhead"> <B> Date </B> </td><td class="colhead"> <B> Notice / Event </B> </td><td class="colhead"> &nbsp; </td> </tr>
             <tr> <td align="right"> 1. </td><td align="left"> UNIVERSITY CALENDAR </td><td align="left">  </td><td align="left">  &nbsp; 13-Aug-2019 &nbsp; </td><td align="left"><a href="https://studentportal.mku.ac.ke/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_477468&fromDate=&toDate="> Please note the following dates on the University Calendar:
            2 nd September, 2019 - Freshers (new  . . .  </a> </td><td align="left">1 </td> </tr>
             <tr> <td align="right"> 2. </td><td align="left"> Notice to all students </td><td align="left">  </td><td align="left">  &nbsp; 06-Aug-2019 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_437964&fromDate=&toDate="> You are kindly notified that Higher Education Loans Board (HELB) first and
            subsequent/continuing  . . .  </a> </td><td align="left">2 </td> </tr>
             <tr> <td align="right"> 3. </td><td align="left"> Proposal and Project Presentation for BIT, BIS and BBIT students REGULAR STUDENTS </td><td align="left">  </td><td align="left">  &nbsp; 30-Jul-2019 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_400263&fromDate=&toDate="> Kindly note that the school will hold presentations for all BIT, BIS and BBIT students who are reg . . .  </a> </td><td align="left">3 </td> </tr>
             <tr> <td align="right"> 4. </td><td align="left"> Proposal and Project Presentation for BIT, BIS and BBIT students VIRTUAL STUDENTS </td><td align="left">  </td><td align="left">  &nbsp; 30-Jul-2019 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_400285&fromDate=&toDate="> Kindly note that the school will hold presentations for all BIT, BIS and BBIT students who are reg . . .  </a> </td><td align="left">4 </td> </tr>
             <tr> <td align="right"> 5. </td><td align="left"> NOTICE TO ALL STUDENTS ON CLASS ATTENDANCE </td><td align="left">  </td><td align="left">  &nbsp; 29-May-2019 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_923184&fromDate=&toDate="> Kindly note that only students who have attained at least 75% lecture
            attendance are eligible to  . . .  </a> </td><td align="left">5 </td> </tr>
             <tr> <td align="right"> 6. </td><td align="left"> NOTICE TO ALL STUDENTS ON CATS </td><td align="left">  </td><td align="left">  &nbsp; 28-May-2019 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_905293&fromDate=&toDate="> Kindly note that Continuous Assessment Tests (CATs) are
            prerequisites for sitting final examinati . . .  </a> </td><td align="left">6 </td> </tr>
             <tr> <td align="right"> 7. </td><td align="left"> Creating Student Emails </td><td align="left">  </td><td align="left">  &nbsp; 04-Oct-2018 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=VKARURU_856373&fromDate=&toDate="> Procedure:
            1. Open Mount Kenya University website ,Student Services ,click Student emails or use  . . .  </a> </td><td align="left">7 </td> </tr>
             <tr> <td align="right"> 8. </td><td align="left"> Official Emails </td><td align="left">  </td><td align="left">  &nbsp; 04-Oct-2018 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_856375&fromDate=&toDate="> The university through the Directorate of ICT is rolling out free email accounts for all students. . . .  </a> </td><td align="left">8 </td> </tr>
             <tr> <td align="right"> 9. </td><td align="left"> MKU Fee Payment Using Mpesa </td><td align="left">  </td><td align="left">  &nbsp; 15-Feb-2018 &nbsp; </td><td align="left"><a href="/umis/studentportal/index.php?realm=noticeDetail&noticeID=AWGITHINJI_561777&fromDate=&toDate="> You can now deposit your fee to our Mount Kenya University account through GT bank using your Mpes . . .  </a> </td><td align="left">9 </td> </tr>
             </table>
	</div>
</div>
{% endblock %}

Portal/core/templates/information_update.html
{% extends 'base.html' %}

{% block nav %}
<div id="navigation" role="navigation">
 <ul id="navigation-primary" class="ult-section primary">   <li class="ult-position">  <a href="{% url 'core:home_page' %}"  class="first">Home</a>
 </li>  <li class="ult-position active">  <a href="{% url 'core:info_update' %}" >Information Update</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:fees_page' %}" >Fees</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:timetable' %}" >Timetables</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:course' %}" >Course Registration</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:results' %}" >Results</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:requests' %}" >My Requests</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:logout_page' %}" >Sign Out</a>
 </li>
</ul><!-- end: .primary -->
  <ul id="navigation-secondary" class="ult-section secondary">   <li class="ult-position  active">  <a href="password_update.php"  class="first">Change Password</a>
 </li>  <li class="ult-position ">  <a href="student_clearance.php" >Student Clearance</a>
 </li>  <li class="ult-position ">  <a href="https://sites.google.com/a/mku.ac.ke/students/" >Downloads</a>
 </li>  <li class="ult-position ">  <a href="http://distance.mku.ac.ke/portal/" target="_blank" > E-Learning Portal </a>
 </li>  <li class="ult-position ">  <a href="https://ibank.gtbank.co.ke/newapps/gtcollectportal/index.aspx" target="_blank" > MPesa Trans. Validation </a>
 </li>  <li class="ult-position ">  <a href="http://studentemailreg.mku.ac.ke/" target="_blank" > Students Email </a>
 </li>
 </ul><!-- end: .secondary -->
 </div><!-- end: #navigation -->
{% endblock %}

{% block content %}
<div class="left_articles">
    <div> <p>BIT/53642/2016 KAINGU STEPHEN TUMAINI  &nbsp;  &nbsp;  &nbsp;  &nbsp; Thika (Day) , Main Campus (Thika)</p></div>
    <table border="1" align="center" cellspacing="0" cellpadding="0">
        <FORM action="/umis/studentportal/personal_information.php" name="varsityProfileForm" enctype="multipart/form-data" method="post">
            <tr> <td align="right" class="dentry_label"> <B> First / Baptism Name:</B> </td>  <td align="left">  &nbsp; STEPHEN</td> </tr>
            <tr> <td align="right" class="dentry_label"> <B> Middle / Given Name:</B> </td>  <td align="left">  &nbsp; TUMAINI</td> </tr>
            <tr> <td align="right" class="dentry_label"> <B> Last / Surname:</B> </td>  <td align="left">  &nbsp; KAINGU</td> </tr>
        </FORM>
    </table>
</div>
{% endblock %}

Portal/core/templates/login.html
{% extends 'base.html' %}

{% block nav %}
<div id="navigation" role="navigation">
 <ul id="navigation-primary" class="ult-section primary">   <li class="ult-position active">  <a href="{% url 'core:home_page' %}"  class="first">Home</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:info_update' %}" >Information Update</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:fees_page' %}" >Fees</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:timetable' %}" >Timetables</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:course' %}" >Course Registration</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:results' %}" >Results</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:requests' %}" >My Requests</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:logout_page' %}" >Sign Out</a>
 </li>
</ul><!-- end: .primary -->
  <ul id="navigation-secondary" class="ult-section secondary">   <li class="ult-position  active">  <a href="password_update.php"  class="first">Change Password</a>
 </li>  <li class="ult-position ">  <a href="student_clearance.php" >Student Clearance</a>
 </li>  <li class="ult-position ">  <a href="https://sites.google.com/a/mku.ac.ke/students/" >Downloads</a>
 </li>  <li class="ult-position ">  <a href="http://distance.mku.ac.ke/portal/" target="_blank" > E-Learning Portal </a>
 </li>  <li class="ult-position ">  <a href="https://ibank.gtbank.co.ke/newapps/gtcollectportal/index.aspx" target="_blank" > MPesa Trans. Validation </a>
 </li>  <li class="ult-position ">  <a href="http://studentemailreg.mku.ac.ke/" target="_blank" > Students Email </a>
 </li>
 </ul><!-- end: .secondary -->
 </div><!-- end: #navigation -->
{% endblock %}

{% block content %}
<div id="left">
	<div class="left_articles"  align="center">
	<div id="body_content" align="center" >

<table border="0" align="center" cellspacing="0" cellpadding="0" >
<tr>
 <td align="center">
<form action="{% url 'core:login_page' %}" name="studentLogon" enctype="multipart/form-data" method="post">
    {% csrf_token %}
<fieldset>
 <legend> Students Login</legend>

<table border="1" align="center" cellspacing="0" cellpadding="0">
<tr>
 <td align="center" colspan="3">
<strong>Registered Students </strong>  </td>
  </tr>
<tr>
 <td align="right">
<B> Student ID / Reg. Number:</B>
   </td>
 <td align="left">
<input type="text" name="regNo" size="20" value="" />  </td>
 <td align="left">
   <i>Type your Student ID / Reg. Number</i> <BR><i>The year of registration must be in full eg ../2010 </i>  </td>
  </tr>
<tr>
 <td align="right">
<B> Password:</B>   </td>
 <td align="left">
<input type="password" name="smisPass" size="20" />    </td>
 <td align="left">
   <i>Use either your  <B> National ID / Passport No.</B> or
   <B> Mobile No.</B> or <B> Telephone No.</B>
  <BR>(Without Spaces) as your initial password</i>
 </td>
  </tr>
<tr>
 <td align="center" colspan="3">
<input type="submit" name="smisLogon" class="inputbutton" value=" &nbsp; &nbsp; Login &nbsp; &nbsp; " />  </td>
  </tr>
</table>
</fieldset>
</form>  </td>
  </tr>
<tr>
 <td align="left">

<table border="0" align="left" cellspacing="0" cellpadding="0" >
<tr>
 <td align="left">
<b> Note: Digits and Letters in your Student ID / Reg. Number.</b><ol><li><b>Digit</b> 0 (Zero) and <b>NOT</b> letter O </li><li><b>Letter</b> I and <b>NOT</b> Digit 1 (One) </li></ol> &nbsp; &nbsp;  </td>
  </tr>
</table>
 </td>
  </tr>
<tr>
 <td align="center">
<form action="{% url 'core:home_page' %}" name="ApplicantOfferLetter" enctype="multipart/form-data" method="post">
    {% csrf_token %}
<fieldset>
 <legend> Applicants / New Students</legend>

<table border="1" align="center" cellspacing="0" cellpadding="0">
<tr>
 <td align="right">
<B> Application Ref. No:</B>
   </td>
 <td align="left">
<input type="text" name="applicationRefNo" size="20" value="" />  </td>
 <td align="left">
   <i>Ref No. or</i> <BR>   <i>Index No / Exam Year</i> <BR><i>The year of registration must be in full eg 01234567001/2015 </i>  </td>
  </tr>
<tr>
 <td align="center" colspan="3">
<input type="submit" name="getLetterOfOfferBtn" class="inputbutton" value=" &nbsp; &nbsp; Generate Letter of Offer &nbsp; &nbsp; " />  </td>
  </tr>
</table>
</fieldset>
</form>  </td>
  </tr>
</table>
</div>	</div>
</div>

{% endblock %}

Portal/core/templates/request.html
{% extends 'base.html' %}

{% block nav %}
<div id="navigation" role="navigation">
 <ul id="navigation-primary" class="ult-section primary">   <li class="ult-position">  <a href="{% url 'core:home_page' %}"  class="first">Home</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:info_update' %}" >Information Update</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:fees_page' %}" >Fees</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:timetable' %}" >Timetables</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:course' %}" >Course Registration</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:results' %}" >Results</a>
 </li>  <li class="ult-position active">  <a href="{% url 'core:requests' %}" >My Requests</a>
 </li>  <li class="ult-position ">  <a href="{% url 'core:logout_page' %}" >Sign Out</a>
 </li>
</ul><!-- end: .primary -->
  <ul id="navigation-secondary" class="ult-section secondary">   <li class="ult-position  active">  <a href="password_update.php"  class="first">Change Password</a>
 </li>  <li class="ult-position ">  <a href="student_clearance.php" >Student Clearance</a>
 </li>  <li class="ult-position ">  <a href="https://sites.google.com/a/mku.ac.ke/students/" >Downloads</a>
 </li>  <li class="ult-position ">  <a href="http://distance.mku.ac.ke/portal/" target="_blank" > E-Learning Portal </a>
 </li>  <li class="ult-position ">  <a href="https://ibank.gtbank.co.ke/newapps/gtcollectportal/index.aspx" target="_blank" > MPesa Trans. Validation </a>
 </li>  <li class="ult-position ">  <a href="http://studentemailreg.mku.ac.ke/" target="_blank" > Students Email </a>
 </li>
 </ul><!-- end: .secondary -->
 </div><!-- end: #navigation -->
{% endblock %}

{% block content %}
<div class="left_articles">
	<div> <p>BIT/53642/2016 KAINGU STEPHEN TUMAINI  &nbsp;  &nbsp;  &nbsp;  &nbsp; Thika (Day) , Main Campus (Thika)</p></div><p class="center">
</p><table cellspacing="0" cellpadding="0" border="0" align="center">
<form action="/umis/studentportal/my_requests_menu.php" name="studentClassTimetable" enctype="multipart/form-data" method="post"></form>
 <tbody><tr> <td align="center">

<table cellspacing="0" cellpadding="0" border="1" align="center">
 <tbody><tr> <td class="dentry_label" align="right"> &nbsp; <b>Request Type :</b>  &nbsp; </td>  <td align="left">
 <select size="1" name="requestTypeID">
 <option value=""> Select Request Type </option>
 <option value="CERTIFICATE">Certificate and Transcript </option>
 <option value="COMPLETIONLETTER">Completion Letter </option>
 <option value="TRANSCRIPT">Transcript </option>
  </select>
 </td> </tr>
 <tr> <td class="dentry_label" align="right"> &nbsp; <b>Collection Method :</b>  &nbsp; </td>  <td align="left">
 <select size="1" name="collectionMethodID">
 <option value=""> Select Collection Method </option>
 <option value="SELF">To be Collected by Self </option>
 <option value="MESSENGER">Collected by Messenger </option>
 <option value="EMPLOYER">Mailed to Employer </option>
 <option value="INSTITUTION">Mailed to another Institution </option>
 <option value="UNIVERSITY">Mailed to another University </option>
 <option value="COURIER">Send by Courier </option>
  </select>
 </td> </tr>
 <tr> <td colspan="2" align="center">
  <input name="newRequestBtn" value="New Request" class="inputbutton" type="submit"> &nbsp;
 </td> </tr>
</tbody></table>


 </td> </tr>
 <tr> <td align="center">
  &nbsp; </td> </tr>
<tr><td align="center">
<table cellspacing="0" cellpadding="0" border="1" align="center">
</table>
</td> </tr>
</tbody></table>
<p></p>	</div>
{% endblock %}